export const InteractionItemType = {
  CARD: 'CARD'
  , FOOD: 'FOOD'
  , TRAIT: 'TRAIT'
  , CARD_TRAIT: 'CARD_TRAIT'
  , TRAIT_SHELL: 'TRAIT_SHELL'
  , ANIMAL_LINK: 'ANIMAL_LINK'
  , PLANT_LINK: 'PLANT_LINK'
  , PLANT_ATTACK: 'PLANT_ATTACK'
  , COVER: 'COVER'
};
