export default {
  GAME_FOOD: 'GAME_FOOD'
  , COOLDOWN: 'COOLDOWN'
  , ANIMAL_CANT_EAT: 'ANIMAL_CANT_EAT'
  , TRAIT_MULTIPLE: 'TRAIT_MULTIPLE'
  , TRAIT_REGENERATION_TRAIT_MAX: 'TRAIT_REGENERATION_TRAIT_MAX'
  , TRAIT_REGENERATION_DEAD: 'TRAIT_REGENERATION_DEAD'
  , PLANT_FOOD: 'PLANT_FOOD'
  , PLANT_FOOD_NO_ACCESS: 'PLANT_FOOD_NO_ACCESS'

  , TRAIT_PLACEMENT_MULTIPLE: 'TRAIT_PLACEMENT_MULTIPLE'
  , TRAIT_PLACEMENT_HIDDEN: 'TRAIT_PLACEMENT_HIDDEN'
  , TRAIT_PLACEMENT_CTT_SELF: 'TRAIT_PLACEMENT_CTT_SELF'
  , TRAIT_PLACEMENT_CTT_ENEMY: 'TRAIT_PLACEMENT_CTT_ENEMY'
  , TRAIT_PLACEMENT_NO_HOST: 'TRAIT_PLACEMENT_NO_HOST'
};